name: Build & publish image

on:
  workflow_call:
    inputs:
      docker-registry:
        type: string
        default: ghcr.io
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      labels:
        type: string
      no-cache-filter:
        required: false
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64
      release:
        type: boolean
        default: true
    secrets:
      registry-password:
        required: true
      registry-username:
        required: true

jobs:
  build:
    name: Build & publish image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3.17
        with:
          detached: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3.5.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ inputs.docker-registry }}/${{ inputs.image-namespace }}/${{ inputs.image-repo }}
          labels: ${{ inputs.labels }}
      - name: Log in to registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.release }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: ${{ inputs.no-cache-filter }}
