name: Test workflows

on:
  pull_request:
  push:
    branches:
      - '**'
  schedule:
    - cron: 25 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=actions/python-versions extractVersion=^(?<version>\S+)-\d+$
      PYTHON_VERSION: 3.12.4
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  run-publish-workflow:
    name: Run `publish` workflow
    needs: pre-commit
    uses: ./.github/workflows/libpublish.yml
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        registry: [docker.io, ghcr.io]
    with:
      docker-registry: ${{ matrix.registry }}
      image-namespace: ${{ github.repository_owner }}
      image-repo: base-docker-build
      labels: org.opencontainers.image.authors=AN Author <author@example.org>
      release: false
    secrets:
      registry-password: ${{ matrix.registry == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}
      registry-username: ${{ github.repository_owner }}
  run-test-workflow:
    name: Run `test` workflow
    needs: pre-commit
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: ${{ github.repository_owner }}
      image-repo: base-docker-build
      release: false
    secrets:
      push-token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs:
      - run-publish-workflow
      - run-test-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Report success
        run: echo "It works!"
      - name: Update Healthchecks.io
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          if [ -n "${HC_UUID}" ]; then
            curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_UUID}
          fi
        env:
          HC_UUID: ${{ secrets.HC_UUID }}
