name: Test workflows

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5.0.0
    - uses: pre-commit/action@v3.0.0
  gri:
    name: Get Docker repo ID
    runs-on: ubuntu-latest
    outputs:
      repo-id: ${{ steps.get-repo-id.outputs.repo-id }}
    steps:
      - id: get-repo-id
        run: |
          REPO_ID=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "repo-id=$REPO_ID" >> $GITHUB_OUTPUT
  run-publish-workflow:
    name: Run `publish` workflow
    needs: gri
    uses: ./.github/workflows/libpublish.yml
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        registry: [docker.io, ghcr.io]
    with:
      docker-registry: ${{ matrix.registry }}
      image-namespace: ${{ github.repository_owner }}
      image-repo: ${{ needs.gri.outputs.repo-id }}
      labels: org.opencontainers.image.authors=AN Author <author@example.org>
      release: false
    secrets:
      registry-password: ${{ matrix.registry == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}
  run-test-workflow:
    name: Run `test` workflow
    needs: gri
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: ${{ github.repository_owner }}
      image-repo: ${{ needs.gri.outputs.repo-id }}
      release: false
    secrets:
      push-token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs:
      - pre-commit
      - run-publish-workflow
      - run-test-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Report success
        run: echo "It works!"
