name: Test workflows

on:
  pull_request:
  push:
    branches:
      - '**'
  schedule:
    - cron: 25 15 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  should-run:
    name: Should run
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.action.outputs.should-run }}
    steps:
      - id: action
        uses: techneg-it/should-workflow-run@eff19348eb884f57e05bc6f05ae48ece3af14714 # v1.0.1
  pre-commit:
    name: Run `pre-commit`
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=custom.python-versions depName=actions/python-versions versioning=pep440
      PYTHON_VERSION: 3.13.7
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  run-publish-workflow:
    name: Run `publish` workflow
    needs: pre-commit
    uses: ./.github/workflows/libpublish.yml
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        registry: [docker.io, ghcr.io]
    with:
      docker-registry: ${{ matrix.registry }}
      image-namespace: ${{ github.repository_owner }}
      image-repo: base-docker-build
      labels: org.opencontainers.image.authors=AN Author <author@example.org>
      build-args: MESSAGE=test message
      no-cache-filter: run
      release: false
    secrets:
      registry-password: ${{ matrix.registry == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}
      registry-username: ${{ github.repository_owner }}
  run-test-workflow:
    name: Run `test` workflow
    needs: pre-commit
    uses: ./.github/workflows/libtest.yml
    with:
      build-args: MESSAGE=test message
      image-namespace: ${{ github.repository_owner }}
      image-repo: base-docker-build
      no-cache-filter: run
  release:
    name: Release
    needs:
      - run-publish-workflow
      - run-test-workflow
    runs-on: ubuntu-24.04
    steps:
      - name: Report success
        run: echo "It works!"
      - name: Update Healthchecks.io
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          if [ -n "${HC_UUID}" ]; then
            curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_UUID}
          fi
        env:
          HC_UUID: ${{ secrets.HC_UUID }}
