name: Build & Test

on:
  pull_request:
  push:
    branches:
      - '**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=custom.python-versions depName=actions/python-versions versioning=pep440
      PYTHON_VERSION: 3.13.0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  run-test-workflow:
    name: Run `test` workflow
    needs:
      - pre-commit
    uses: ./.github/workflows/libtest.yml
    permissions:
      contents: write
    with:
      image-namespace: dafyddj
      image-repo: base-docker-build
    secrets:
      push-token: ${{ secrets.PUSH_TOKEN }}
